language: c

os:
  - linux

dist: xenial

install:
  - curl -sL https://github.com/gohugoio/hugo/releases/download/v0.79.0/hugo_0.79.0_Linux-64bit.tar.gz | sudo tar xzv -C /usr/bin/

script:
  - hugo
  - git add -f public && git commit -a -m "travis-ci auto commit"

deploy:
  provider: pages
  strategy: git
  cleanup: false
  local_dir: public
  target_branch: gh-pages
  token: $GITHUB_API_TOKEN
  name: l10178
  email: l10178@163.com
  on:
    branch: master
