baseURL: 'https://l10178.github.io/idaas-book/'
languageCode: 'zh-CN'
title: 'A book about IDaaS'
theme: hugo-geekdoc
pygmentsUseClasses: true
pygmentsCodeFences: true

# Geekdoc configuration
disablePathToLower: true
enableGitInfo: true

# Needed for mermaid shortcodes
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
    endLevel: 9

params:
  geekdocToC: 3
  # (Optional, default true) Show a breadcrumb navigation bar at the top of each docs page.
  # You can also specify this parameter per page in front matter.
  geekdocBreadcrumb: false

  # relative to your 'static/' folder.
  geekdocLogo: 'images/logos/logo.png'

  # (Optional, default none) Set source repository location
  # Used for 'Edit this page' links
  # You can also specify this parameter per page in front matter.
  geekdocRepo: 'https://github.com/l10178/idaas-book'

  # (Optional, default none) Enable "Edit this page" links. Requires 'GeekdocRepo' param
  # and path must point to 'content' directory of repo.
  # You can also specify this parameter per page in front matter.
  geekdocEditPath: edit/main/content

  # (Optional, default true) Add an anchor link to headlines.
  geekdocAnchor: false

  # (Optional, default true) Copy anchor url to clipboard on click.
  geekdocAnchorCopy: false
