name: docker nightly

on:
  push:
  schedule:
    - cron: '0 19 * * *' #每天在国际标准时间19点（北京时间早上3点）

env:
  IMAGE_NAME: idaas-book
  TAG_NAME: nightly
  HUGO_BASE_URL: https://www.nxest.com/idaas-book/

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.80.0'

      - name: Build
        run: hugo --minify --baseURL $HUGO_BASE_URL

      - name: Login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Setup buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Push image
        run: |
          docker buildx build \
            --tag nxest/$IMAGE_NAME:$TAG_NAME \
            --platform linux/amd64,linux/arm64 \
            -f Dockerfile ./ \
            --push
